export const MUT_APP_TYPES = {
  SET_NAME: 'SET_APP_NAME',
  SET_LOGO: 'SET_APP_LOGO',
  SET_LOGIN_PIC: 'SET_APP_LOGIN_PIC',
  SET_SCREEN_SIZE: 'SET_SCREEN_SIZE',
  SET_LAYOUT: 'SET_LAYOUT',
  SET_HEADER_FIXED: 'SET_HEADER_FIXED',
  SET_SIDEBAR_FIXED: 'SET_SIDEBAR_FIXED',
  SET_SIDEBAR_COLLAPSED: 'SET_SIDEBAR_COLLAPSED',
  SET_SIDEBAR_OPENED: 'SET_SIDEBAR_OPENED',
  SET_BREADCRUMB_WRAPPER: 'SET_BREADCRUMB_WRAPPER',
  SET_ENABLE_SETTING: 'SET_ENABLE_SETTING'
}

export const MUT_USER_TYPES = {
  SET_TOKEN: 'SET_TOKEN',
  SET_USER: 'SET_USER',
  SET_ROLE: 'SET_ROLE'
}

export const permissionTypes = {
  SET_ROUTERS: 'SET_ROUTERS'
}
