export const appTypes = {
  SET_SCREEN_SIZE: 'SET_SCREEN_SIZE',
  SET_SIDER_FIXED: 'SET_SIDER_FIXED',
  SET_SIDER_COLLAPSED: 'SET_SIDER_COLLAPSED',
  SET_SIDER_OPENED: 'SET_SIDER_OPENED',
  SET_DISABLE_ANIMATION: 'SET_DISABLE_ANIMATION'
}

export const userTypes = {
  SET_USERID: 'SET_USERID',
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN'
}

export const permissionTypes = {
  SET_ROUTERS: 'SET_ROUTERS'
}