const fontFormats =
  '宋体=SimSun;' +
  '新宋体=NSimSun;' +
  '仿宋=FangSong;' +
  '细明体=MingLiU;' +
  '新细明体=PMingLiU;' +
  '楷体=KaiTi;' +
  '标楷体=DFKai-SB;' +
  '黑体=SimHei;' +
  '微软雅黑=Microsoft YaHei;' +
  'Andale Mono=andale mono,times;' +
  'Arial=arial,helvetica,sans-serif;' +
  'Arial Black=arial black,avant garde;' +
  'Book Antiqua=book antiqua,palatino;' +
  'Comic Sans MS=comic sans ms,sans-serif;' +
  'Courier New=courier new,courier;' +
  'Georgia=georgia,palatino;' +
  'Helvetica=helvetica;' +
  'Impact=impact,chicago;' +
  'Symbol=symbol;' +
  'Tahoma=tahoma,arial,helvetica,sans-serif;' +
  'Terminal=terminal,monaco;' +
  'Times New Roman=times new roman,times;' +
  'Trebuchet MS=trebuchet ms,geneva;' +
  'Verdana=verdana,geneva;' +
  'Webdings=webdings;' +
  'Wingdings=wingdings,zapf dingbats'

export default fontFormats
